POST http://localhost:9528/wxbot/callback
Content-Type: application/json

{
  "code": 200,
  "data": {
    "isAt": false,
    "appInfo": {
      "type": 0,
      "appID": ""
    },
    "appMsgType": 0,
    "hasProductId": 0,
    "imgHeight": 0,
    "imgStatus": 1,
    "imgWidth": 0,
    "forwardFlag": 0,
    "msgType": 1,
    "status": 3,
    "statusNotifyCode": 0,
    "subMsgType": 0,
    "voiceLength": 0,
    "createTime": 1719301639,
    "newMsgId": 5587273746519589685,
    "playLength": 0,
    "mediaId": "",
    "msgId": "5587273746519589685",
    "encryFileName": "",
    "fileName": "",
    "fileSize": "",
    "content": "你好",
    "fromerName": "@32a10f296603115b92cb2e7bc292d74e",
    "oriContent": "",
    "statusNotifyUserName": "",
    "ticket": "",
    "toUserName": "@148e5de16760fe8c4bd617a8e1b98dd1a62cd34bf893b597da60f69cc19a6b53",
    "url": "",
    "recommendInfo": {
      "OpCode": 0,
      "Scene": 0,
      "Sex": 0,
      "VerifyFlag": 0,
      "AttrStatus": 0,
      "QQNum": 0,
      "Alias": "",
      "City": "",
      "Content": "",
      "NickName": "",
      "Province": "",
      "Signature": "",
      "Ticket": "",
      "UserName": ""
    },
    "attachmentUrl": "",
    "groupSenderInfo": {
      "wxId": "",
      "nickName": ""
    }
  }
}


### 添加模型
#POST http://localhost:9528/ai/model/upsert/batch
POST https://wxbot.h.zmlz.net/ai/model/upsert/batch
Content-Type: application/json

[
  {
    "model": "glm-4",
    "name": "glm4",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1.0,
    "presencePenalty": 0.0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "type": "TEXT"
  },
  {
    "model": "glm-v",
    "name": "glmv",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1.0,
    "presencePenalty": 0.0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "type": "TEXT"
  },
  {
    "model": "coze",
    "name": "coze",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1,
    "presencePenalty": 0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "type": "TEXT"
  },
  {
    "model": "abab6.5-chat",
    "name": "abab65",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1,
    "presencePenalty": 0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "type": "TEXT"
  },
  {
    "model": "abab5.5s-chat",
    "name": "abab55s",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1,
    "presencePenalty": 0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "type": "TEXT"
  }
]

### 添加默认模型
#POST http://localhost:9528/ai/default-model/upsert/batch
POST https://wxbot.h.zmlz.net/ai/default-model/upsert/batch
Content-Type: application/json

[
  {
    "modelName": "coze",
    "Type": "IMAGE"
  },
  {
    "modelName": "glm-4",
    "Type": "TEXT"
  }
]

### 获取模型
#GET http://localhost:9528/ai/model/list
GET https://wxbot.h.zmlz.net/ai/model/list


### 获取模型
#GET http://localhost:9528/ai/default-model/list
GET https://wxbot.h.zmlz.net/ai/default-model/list


### 修改回调地址
POST https://wx.h.zmlz.net/api/v1/robot/callback/config/update
Content-Type: application/json

{
    "host": "http://wxbot:9528",
  "msgCallbackPath": "/wxbot/callback"
}

### 发送图片消息
POST https://wx.h.zmlz.net/api/v1/robot/file/send
Content-Type: application/json

{
  "wxId": "@745cc2ea6b780ee7f9d542a504cb84dd",
  "url": "https://web-static.4ce.cn/storage/bucket/v1/fa6b91478b78fe0f5462f3c5dbf23ff2.png",
  "fileType": 0
}

### 查看bot信息
### 修改回调地址
GET https://wx.h.zmlz.net/api/v1/robot/info
Content-Type: application/json


[
  {
    "model": "glm-4",
    "name": "glm4",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1.0,
    "presencePenalty": 0.0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "toolCalls": [],
    "toolCallID": "",
    "supportType": "TEXT",
    "isDefault": true
  },
  {
    "model": "coze",
    "name": "coze",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1,
    "presencePenalty": 0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "toolCalls": [],
    "toolCallID": "",
    "supportType": "TEXT",
    "isDefault": false
  },
  {
    "model": "abab6.5-chat",
    "name": "abab65",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1,
    "presencePenalty": 0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "toolCalls": [],
    "toolCallID": "",
    "supportType": "TEXT",
    "isDefault": false
  },
  {
    "model": "abab5.5s-chat",
    "name": "abab55s",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1,
    "presencePenalty": 0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "toolCalls": [],
    "toolCallID": "",
    "supportType": "TEXT",
    "isDefault": false
  },
  {
    "model": "coze",
    "name": "dalle3",
    "maxTokens": 4096,
    "temperature": 0.8,
    "topP": 1,
    "presencePenalty": 0,
    "frequencyPenalty": 0.6,
    "imageSize": "512x512",
    "toolCalls": [],
    "toolCallID": "",
    "supportType": "IMAGE",
    "isDefault": true
  }
]