// Code generated by wxbot project. DO NOT EDIT.
// Source: github.com/yqchilde/wxbot/engine/plugins/generate.go

package plugins

import (
	//_ "github.com/yqchilde/wxbot/plugins/baidubaike"

	//_ "github.com/yqchilde/wxbot/plugins/crazykfc"

	//_ "github.com/yqchilde/wxbot/plugins/ghmonitor"

	//_ "github.com/yqchilde/wxbot/plugins/manager"

	//_ "github.com/yqchilde/wxbot/plugins/memepicture"

	// _ "github.com/yqchilde/wxbot/plugins/moyuban"

	// _ "github.com/yqchilde/wxbot/plugins/pinyinsuoxie"

	//_ "github.com/yqchilde/wxbot/plugins/plmm"

	// _ "github.com/yqchilde/wxbot/plugins/weather"

	//_ "github.com/yqchilde/wxbot/plugins/zaobao"

	//_ "github.com/yqchilde/wxbot/plugins/wordcloud"

	//_ "github.com/yqchilde/wxbot/plugins/chaid"

	// _ "github.com/yqchilde/wxbot/plugins/youdaofanyi"

	//_ "github.com/yqchilde/wxbot/plugins/friendadd"

	//_ "github.com/yqchilde/wxbot/plugins/choose"

	//_ "github.com/yqchilde/wxbot/plugins/localimage"

	//_ "github.com/yqchilde/wxbot/plugins/localimagespider"

	// AI聊天，优先级必须放到最低
	_ "github.com/yqchilde/wxbot/plugins/ai"
	// _ "github.com/yqchilde/wxbot/plugins/chatgpt"
)
